name: DEV CI
on:
  push:
    branches:
      - dev
      - stage
      - feature/**
jobs:
  dev-build:
    uses: ./.github/workflows/reusable-ci.yml

    with:
      environment_name: dev
      branch_ref: ${{ github.ref }}
      s3_folder: dev

    secrets: inherit
