name: DEV CI

on:
  push:
    branches:
      - dev
      - stage
      - feature/**

jobs:
  dev-build:
    uses: ./.github/workflows/reusable-ci.yml

    with:
      branch_name: dev
      s3_env: dev

    secrets: inherit
