name: PROD CI

on:
  workflow_dispatch:

jobs:
  prod-build:
    uses: ./.github/workflows/reusable-ci.yml

    with:
      environment_name: prod
      branch_ref: refs/heads/main
      s3_folder: prod

    secrets: inherit
