name: PROD CI Build - Main Branch Deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/dev-ci-new.yml'
      - 'README.md'
      - '.gitignore'
  workflow_dispatch:

jobs:
  prod-build:
    name: Build and Deploy to PROD
    uses: ./.github/workflows/reusable-ci.yml
    with:
      environment_name: 'prod'
      branch_ref: 'main'
      s3_folder: 'prod'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
