name: PROD-CI

on:
  workflow_dispatch: # This is the key for manual triggers

jobs:
  prod-build:
    uses: ./.github/workflows/reusable-ci.yml
    with:
      environment_name: prod
      branch_ref: ${{ github.ref_name }} 
      repo_name: ${{ github.event.repository.name }}
      run_version: ${{ github.run_number }}
    secrets: inherit
