name: Reusable CI Pipeline

on:
  workflow_call:

    inputs:
      environment_name:
        required: true
        type: string

      branch_ref:
        required: true
        type: string

      s3_folder:
        required: true
        type: string

    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true


jobs:
  build:
    runs-on: windows-latest
    environment: ${{ inputs.environment_name }}

    env:
      CONFIGURATION: Release
      PROJECT_NAME: ClientExtras
      S3_BUCKET: mybucketp03

    steps:

      # Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch_ref }}

      # Setup .NET
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '5.0.x'

      # Extract branch name
      - name: Extract Branch Name
        shell: pwsh
        run: |
          $branch = "${{ inputs.branch_ref }}" -replace "refs/heads/", ""
          echo "BRANCH_NAME=$branch" >> $env:GITHUB_ENV
          Write-Host "Branch: $branch"

      # AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Build Date + Build Number
      - name: Generate Build Info
        shell: pwsh
        run: |
          $ist = [System.TimeZoneInfo]::ConvertTimeBySystemTimeZoneId((Get-Date),'India Standard Time')
          $buildDate = $ist.ToString("yyyyMMdd")

          $s3Path = "s3://$env:S3_BUCKET/ClientExtras/${{ inputs.s3_folder }}/"

          $files = aws s3 ls $s3Path --region "${{ secrets.AWS_REGION }}"

          if ($LASTEXITCODE -eq 0 -and $files) {
            $count = ($files | Where-Object { $_ -match "$env:BRANCH_NAME_$buildDate" }).Count
          } else {
            $count = 0
          }

          $buildNumber = $count + 1

          echo "BUILD_DATE=$buildDate" >> $env:GITHUB_ENV
          echo "BUILD_NUMBER=$buildNumber" >> $env:GITHUB_ENV

      # Restore
      - name: Restore
        run: dotnet restore .\trunk\ClientExtras.sln

      # Build
      - name: Build
        run: dotnet build .\trunk\ClientExtras.sln --configuration ${{ env.CONFIGURATION }} --no-restore

      # Publish
      - name: Publish
        run: |
          dotnet publish .\trunk\Services\Client.WebApi\Client.WebApi.csproj `
            --configuration ${{ env.CONFIGURATION }} `
            --output .\publish

      # Rename folder
      - name: Rename Output
        shell: pwsh
        run: Rename-Item .\publish "publish_$env:BUILD_DATE_$env:BUILD_NUMBER"

      # ZIP
      - name: Create ZIP
        shell: pwsh
        run: |
          $zip = "$env:BRANCH_NAME_$env:BUILD_DATE_$env:BUILD_NUMBER.zip"
          Compress-Archive -Path "publish_*" -DestinationPath $zip
          echo "ZIP_FILE=$zip" >> $env:GITHUB_ENV

      # Upload to S3
      - name: Upload
        shell: pwsh
        run: |
          aws s3 cp "$env:ZIP_FILE" "s3://$env:S3_BUCKET/ClientExtras/${{ inputs.s3_folder }}/"

      # Summary
      - name: Summary
        run: |
          Write-Host "Env: ${{ inputs.environment_name }}"
          Write-Host "Branch: $env:BRANCH_NAME"
          Write-Host "File: $env:ZIP_FILE"
